spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
  data:
    cassandra:
      keyspace-name: taco_cloud
      schema-action: recreate
      local-datacenter: datacenter1
      username: tacocloud
      password: s3cr3tP455W0rd